194 feature request shareing through email identifier instead of subject identifier sub
SchweizerischeBundesbahnen/netzgrafik-editor-frontend pull request #195
Opened 2024-07-24 06:50 UTC by aiAdrian

# Description

This pull request requires as well the backend pull request **https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-backend/pull/16**

User can now enter partner's email adresse to share projects. 

## Examples
![image](https://github.com/user-attachments/assets/7934e6ad-fe62-4032-941e-e0b1f43476c1)

![image](https://github.com/user-attachments/assets/9cff0f85-aac3-41ff-abc3-90defd56f24b)

2024-07-24 12:34 UTC, chenkins requested changes
Main design comments in [backend pr review ](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-backend/pull/16#pullrequestreview-2196348079), only two minor change requests here.

2024-07-24 12:34 UTC, chenkins commented on src/app/view/project/project-dialog/project-form/project-form.component.ts
> +    !id.match(/^([a-z0-9_\\.-]+)@([\da-z\\.-]+)\.([a-z\\.]{2,6})$/));
@aiAdrian "Magic pattern": Extract pattern and name it. Add unit test for the pattern showing the correctness of the pattern, also with non-matching examples.

2024-07-24 12:34 UTC, chenkins commented on src/app/view/project/project-dialog/project-form/project-form.component.ts
> +  const invalidIds = userIds.filter((id) =>
@aiAdrian rename variable to `invalidEmails`. Also rename `userIdsValidator`

2024-07-25 09:08 UTC, aiAdrian commented on src/app/view/project/project-dialog/project-form/project-form.component.ts
> +  const invalidIds = userIds.filter((id) =>
done

2024-07-25 09:08 UTC, aiAdrian commented on src/app/view/project/project-dialog/project-form/project-form.component.ts
> +    !id.match(/^([a-z0-9_\\.-]+)@([\da-z\\.-]+)\.([a-z\\.]{2,6})$/));
done and test added

2024-07-25 10:22 UTC, chenkins approved these changes

2024-07-25 10:23 UTC, chenkins approved these changes

2024-07-29 14:22 UTC, louisgreiner approved these changes
Lgtm, translation will have to take this PR in account too

2024-07-31 08:12 UTC, emersion commented on src/app/view/project/project-dialog/project-form/project-form.component.ts
> +      id.match(/^([a-z0-9_\\.-]+)@([\da-z\\.-]+)\.([a-z\\.]{2,6})|(u|ue|e)\d+$/);
Same as https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-backend/pull/16/files#r1698074806: this is too restrictive.

2024-07-31 08:13 UTC, emersion commented on src/app/view/variant/variant-view/variant-history/version-entry-layout/version-entry-layout.component.scss
> +  min-width: 275px;
Would we be able to avoid hardcoding sizes in pixels here?

2024-07-31 12:13 UTC, aiAdrian commented on src/app/view/variant/variant-view/variant-history/version-entry-layout/version-entry-layout.component.scss
> +  min-width: 275px;
Oh  - It was undone - not intentionally committed!

2024-07-31 13:24 UTC, merged