WIP
SchweizerischeBundesbahnen/netzgrafik-editor-frontend pull request #301
Opened 2024-10-01 11:55 UTC by shenriotpro

# Description

# Issues

# Checklist

* [ ] This PR contains a description of the changes I'm making
* [ ] I've read the [Contribution Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/CONTRIBUTING.md)
* [ ] I've added tests for changes or features I've introduced
* [ ] I documented any high-level concepts I'm introducing in `documentation/`
* [ ] CI is currently green and this is ready for review

2024-10-08 07:46 UTC, shenriotpro commented
@louisgreiner @jacomyal

2024-10-08 15:58 UTC, louisgreiner reviewed
Thank you for the excellent documentation that makes this new feature easy to read. The code is also very cleaned

I just wonder if some variable names would not be better if they could be more explicit. I commented a few things about that, feel free to ignore if it adds too much noise.

Overall high quality code, it needs to be challenged by the users. Next step is implementing an interface and optimizing

PS: the test unit is very good 🥇

2024-10-08 15:58 UTC, louisgreiner commented on src/app/view/util/origin-destination-graph.ts
> +      public departure: boolean,
```suggestion
      public isDeparture: boolean,
```

2024-10-08 15:58 UTC, louisgreiner commented on src/app/view/util/origin-destination-graph.ts
> +      public trainrun?: number
```suggestion
      public trainrunId?: number
```

2024-10-08 15:58 UTC, louisgreiner commented on src/app/view/util/origin-destination-graph.ts
> +      let ns = false;
```suggestion
      let nonStop = false;
```

2024-10-08 15:58 UTC, louisgreiner commented on src/app/view/util/origin-destination-graph.ts
> +const dfs = (graph: Map<string, [Vertex, number][]>, root: Vertex, visited: Set<string>, res: Vertex[]): void => {
```suggestion
const depthFirstSearch = (graph: Map<string, [Vertex, number][]>, root: Vertex, visited: Set<string>, res: Vertex[]): void => {
```

2024-10-10 11:52 UTC, aiAdrian requested changes

2024-10-10 11:52 UTC, aiAdrian commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
>      headers.push($localize`:@@app.view.editor-side-view.editor-tools-view-component.origin:Origin`);
It would be nice if the short name of origin and destination nodes could also be exported.

2024-10-10 11:52 UTC, aiAdrian commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
> +    const connectionPenalty = 5;
Good to start with a constant. It might be a good option to store or read this value in the metadata (internal data (JSON) META data). This would make it easy to edit the planning basis at a later date. Or we can use a JSON manual -> could be worth doing this 

```code
 metadata: {
        analyticsSettings { 
             originDestinationSettings { 
                connectionPenalty: 5
             }
        }
        trainrunCategories: [ ... ] 
        ... 
} 
```
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/main/src/app/sample-netzgrafik/netzgrafik.default.ts

Feel free to make a proposal how to store the settings in the JSON. Don't forget to extend the migration stuff when adding new metadata 
https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-frontend/blob/03d44a00401bc45bddc9a3acd967fdd1689006fe/src/app/utils/data-migration.ts

2024-10-10 11:52 UTC, aiAdrian commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
> +    const timeLimit = 10*60;
Why: 10 * 60 - what is this limit for?

2024-10-10 11:52 UTC, aiAdrian commented on src/app/services/data/trainrun.service.ts
> +  // For each trainrun, get iterators from the source (trainruns may be split).
Do we need a Train Run Iterator for the two end nodes (start, destination)? It might be easier to read if we implement the code as shown below. I briefly inserted it this way, but then all the tests related to this topic failed. Could you please check quickly whether the idea is correct but implemented incorrectly, or explain to me in 2-3 sentences what exactly is being done—potentially directly in the code. Furthermore, my suggestion could be much slower, but this still needs to be tested if the suggestion calculates correctly. But I have to say that I don't understand the implementation 100% in detail.

```
  public getRootIterators(): Map<number, TrainrunIterator[]> {
    const iterators = new Map<number, TrainrunIterator[]>();
    this.getTrainruns().forEach((tr: Trainrun) => {
      const bothSideNodes = this.getBothEndNodesWithTrainrunId(tr.getId());
      const bothSideIterators: TrainrunIterator[] = [];
      bothSideIterators.push(this.getIterator(bothSideNodes.endNode1, bothSideNodes.endNode1.getStartTrainrunSection(tr.getId())));
      bothSideIterators.push(this.getIterator(bothSideNodes.endNode2, bothSideNodes.endNode2.getStartTrainrunSection(tr.getId())));
      iterators.set(tr.getId(), bothSideIterators);
    });
    return iterators;
  }
```
TrainrunService.getBothEndNodesWithTrainrunId(trainrunId)

2024-10-10 11:54 UTC, shenriotpro commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
>      headers.push($localize`:@@app.view.editor-side-view.editor-tools-view-component.origin:Origin`);
I switched to short names yesterday, so that the CSV is more readable.

2024-10-10 11:56 UTC, shenriotpro commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
> +    const timeLimit = 10*60;
It's a bit arbitrary, I'm not sure how long a typical daily schedule is (16 hours ?), we can increase it a bit if optimization works well.

2024-10-10 12:08 UTC, shenriotpro commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
> +    const connectionPenalty = 5;
I see, do you mind if we do that in another PR?

2024-10-10 12:41 UTC, shenriotpro commented on src/app/services/data/trainrun.service.ts
> +  // For each trainrun, get iterators from the source (trainruns may be split).
Tests pass if I comment out the first push (the iterator is automatically reversed later).
The current version is designed to handles cases where there are more than 2 end nodes (what I call split trainruns), but perhaps that was a bit optimistic, I can change if you prefer.

2024-10-10 12:43 UTC, shenriotpro commented on src/app/services/data/trainrun.service.ts
> +  // For each trainrun, get iterators from the source (trainruns may be split).
The performance impact doesn't seem to be significant.

2024-10-10 12:45 UTC, aiAdrian commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
> +    const connectionPenalty = 5;
That's fine.

2024-10-10 12:46 UTC, aiAdrian commented on src/app/view/editor-tools-view-component/editor-tools-view.component.ts
> +    const timeLimit = 10*60;
24h ? but we start with 10 hours

2024-10-10 12:51 UTC, aiAdrian commented on src/app/services/data/trainrun.service.ts
> +  // For each trainrun, get iterators from the source (trainruns may be split).
Your method is better! Thanks - well done. igonore my suggestion.

2024-10-10 13:07 UTC, aiAdrian approved these changes
Very nice work!

2024-10-10 13:11 UTC, merged